'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'
'     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
'     der Code wird erneut generiert. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Manage

    '''<summary>
    '''successMessage-Steuerelement
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents successMessage As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''setPassword-Steuerelement
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents setPassword As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''password-Steuerelement
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents password As Global.System.Web.UI.WebControls.TextBox

    
    '''<summary>
    '''newPasswordMessage-Steuerelement
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents newPasswordMessage As Global.System.Web.UI.WebControls.Label
    

    '''<summary>
    '''confirmPassword-Steuerelement
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents confirmPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''changePassword-Steuerelement
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents changePassword As Global.System.Web.UI.WebControls.PlaceHolder

    
    '''<summary>
    '''externalLoginsList-Steuerelement
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents externalLoginsList As Global.System.Web.UI.WebControls.ListView
    
End Class
